version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    container_name: users-api
    build:
      context: ./
      target: production
    image: users-api
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - NODE_ENV
      - DB_USER
      - DB_PASSWORD
      - DB_PORT
      - DB_HOST
    links:
      - db
    volumes:
      - ./:/src
      - /src/node_modules
volumes:
  db:
    driver: local
