version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - DB_USER
      - DB_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db:/db
  api:
    container_name: same-it
    build:
      context: ./
      target: production
    image: same-it
    depends_on:
      - "db"
    ports:
      - 3000:3000
    environment:
      - NODE_ENV
      - DB_USER
      - DB_PASSWORD
      - DB_PORT
      - DB_HOST
    links:
      - db
    volumes:
      - ./:/src
      - /src/node_modules
volumes:
  db:
    driver: local
